services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///pr2.db
    volumes:
      - ./instance:/app/data
    depends_on:
      - db

  db:
    image: jitesoft/sqlite
    volumes:
      - ./instance:/app/data
