version: '3'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./instance:/app/instance"
      - "/var/webapp/lab1/images:/app/images"
      - "/var/webapp/lab1/images/download:/app/download"
